export const white = '#fff'; // white light - white-main dark
export const gray1 = '#F2F2F2';
export const gray2 = '#D5D8DB';
export const gray3 = '#F2F4F9';
export const gray4 = '#ADB5BD';
export const gray5 = '#AAAAAA';
export const gray6 = '#7E8387';
export const gray7 = '#1D2338'; //black light
export const gray8 = '#E2E2E2'; //White-text dark
export const gray9 = '#A2A2A2'; //gray4 dark
export const gray10 = '#616161'; //gray6 dark
export const gray11 = '#1E1E1E'; //bg-second dark
export const gray12 = '#121212'; //bg-black dark
export const gray13 = '#2C2C2C'; //bg-third dark
export const black = '#000';
export const green = '#00BA51';
export const red = '#FA163F';
export const yellow = '#FFCD3C';
export const blue = '#2F80ED';
export const blueLight = '#EFFFDB'; //bg_screens
